version: '3.8'

services:

  back:
    working_dir: /var/www
    build:
      context: ./back
      dockerfile: Dockerfile.fpm
      target: dev-build
    volumes:
      - ./back:/var/www
      - ./back/.docker/fpm/custom.ini:/usr/local/etc/php-fpm.d/www.conf
      - ./back/.docker/fpm/php.ini:/usr/local/etc/php/conf.d/php-add.ini
      - ./back/.docker/config/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

  back_nginx:
    image: nginx:1.19.8
    ports:
      - "80:80"
    depends_on:
      - back
    volumes:
      - ./back:/var/www
      - ./nginx/docker/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/docker/sites/:/etc/nginx/sites-available
      - ./nginx/docker/conf.d.dev/:/etc/nginx/conf.d
    logging:
      driver: "json-file"
      options:
        max-size: "5m"

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: gog_assignment
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3306:3306"
      
  redis_session_storage:
    image: redis
    command: redis-server --requirepass 1234

volumes:
  db: {}
