FROM nginx:1.19.8 as base

# ##########################
FROM base AS prod-build

COPY ./docker/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/sites/. /etc/nginx/sites-available/
COPY ./docker/conf.d/. /etc/nginx/conf.d/
# dummy php file only for symfony front-controller try_files
COPY ./docker/back/index.php /var/www/public/index.php
